#!/bin/bash
algorithm_path=".."

./generate-html

echo
echo "Generating PDF Cover"
./wkhtmltopdf --title "[Leewings] Algorithm Library" cover.html cover.pdf

echo
echo "Generating PDF"
./wkhtmltopdf --title "[Leewings] Algorithm Library" --book --toc-header-font-size 20 --toc-l1-font-size 16 --toc-l2-font-size 14 --toc-l3-font-size 12 --header-right '- [page] -' --header-spacing 1 --cover frontpage.html "Leewings Algorithm Library.html" "Leewings Algorithm Library.pdf"
